sudo: required
services:
  - docker

before_install:
  - docker build -t stevenaimm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stevenaimm/docker-react npm run test -- --coverage